---
grafana_download_url: "https://disk.yandex.ru/d/owQnAkjG6KpIuQ"
grafana_config_dir: /etc/grafana
grafana_config_file: "grafana.conf.j2"
service_name: "grafana-server"
grafana_url: "http://localhost:3000"
grafana_user: "admin"
grafana_password: "admin"
grafana_version: "latest"
grafana_prometheus: true
data_source:
  - name: "prometheus"
    ds_type: "prometheus"
    url: "http://localhost:9090"