---
- name: nginx_role
  src: git@github.com:kirill-karagodin/nginx-role.git
  scm: git
  version: "1.0.2"
#- name: alertmanager_role
#  src: git@github.com:cloudalchemy/ansible-alertmanager.git
#  scm: git
#  version: "0.19.1"