---
# Install Jenkins Master
- name: Install Jenkins Master
  import_tasks: tasks/jenkins_task.yml

# Install Grafana
- name: Install Grafana on master server
  hosts: grafana-master
  import_tasks: tasks/grafana_task.yml

# Install Prometheus on master server
- name: Install Prometheus on master server
  hosts: grafana-master
  import_tasks: tasks/prometheus_task.yml

# Out URL
#  post_tasks:
#    - name: Show connect URL's
#      debug:
#        msg: "Jenkins Master http://{{ ansible_host }}"
#        msg: "Grafana http://{{ ansible_host }}"

