---
all:
  hosts:
    jenkins-master-01:
      ansible_host: <master>
    grafana-master-01:
      ansible_host: <grafana>
    jenkins-agent-stage-01:
      ansible_host: ${yandex_compute_instance.stage-agent1.network_interface.0.nat_ip_address}
	  jenkins-agent-prod=01:
      ansible_host: ${yandex_compute_instance.prod-agent1.network_interface.0.nat_ip_address}
    prometheus-master-01:
      ansible_host: <grafana>
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agent:
          hosts:
			      jenkins-agent-stage-01:
			      jenkins-agent-prod-01:
    grafana:
      children:
        grafana-master:
          hosts:
            grafana-master-01:
    prometheus:
      children:
        prometheus-master:
          hosts:
            prometheus-master-01:

  vars:
    ansible_connection_type: paramiko
    ansible_user: <user>