---
- name: create prometheus system group
  become: true
  group:
    name: "{{ prometheus_user_group }}"
    state: present

- name: create prometheus system user
  become: true
  user:
    name: "{{ prometheus_user_name }}"
    group: "{{ prometheus_user_group }}"
    system: true
    shell: "/sbin/nologin"
    comment: "prometheus nologin user"
    createhome: false
    state: present

- name: download prometheus binary to local folder
  become: true
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_ver }}/prometheus-{{ prometheus_ver }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_ver }}.linux-amd64.tar.gz"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: unpack prometheus binaries
  become: true
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_ver }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-{{ prometheus_ver }}.linux-amd64/prometheus"
  check_mode: false

- name: propagate prometheus and promtool binaries
  become: true
  copy:
    src: "/tmp/prometheus-{{ prometheus_ver }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: "{{ prometheus_user_name }}"
    group: "{{ prometheus_user_group }}"
    remote_src: yes
    mode: 0755
  with_items:
    - prometheus
    - promtool

- name: create prometheus data directory
  become: true
  file:
    path: "{{ prometheus_dir }}"
    state: directory
    owner: "{{ prometheus_user_name }}"
    group: "{{ prometheus_user_group }}"
    mode: 0755

- name: create prometheus config directory
  become: true
  file:
    path: "{{ prometheus_confdir }}"
    state: directory
    owner: "{{ prometheus_user_name }}"
    group: "{{ prometheus_user_group }}"
    mode: 0755

- name: propagate official console templates
  become: true
  copy:
    src: "/tmp/prometheus-{{ prometheus_ver }}.linux-amd64/{{ item }}/"
    dest: "{{ prometheus_confdir }}/{{ item }}/"
    remote_src: yes
    mode: 0644
    owner: "{{ prometheus_user_name }}"
    group: "{{ prometheus_user_group }}"
  with_items:
    - console_libraries
    - consoles

- name: delete prometheus tmp folder and .tar.gz file
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/prometheus-{{ prometheus_ver }}.linux-amd64
    - /tmp/prometheus-{{ prometheus_ver }}.linux-amd64.tar.gz

- name: configure prometheus
  become: true
  template:
    src: "{{ prometheus_conffile }}"
    dest: "{{ prometheus_confdir }}/prometheus.conf"

- name: alert config file
  become: true
  copy:
    src: "files/alertrules.yml"
    dest: //etc/prometheus/alert.rules.yml

- name: create systemd service unit
  become: true
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: reload_systemd

- name: start prometheus service
  become: true
  service:
    name: "{{ serv_name }}"
    state: started
    enabled: yes

- name: check if prometheus is accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
