---
- name: restart the grafana service
  service:
    name: "{{ service_name }}"
    state: restarted
  listen: event_restart_grafana

- name: reload systemd
  command: systemctl daemon-reload
  listen: reload_systemd

