---
- name: restart the prometheus service
  service:
    name: "{{ serv_name }}"
    state: restarted
  listen: event_restart_prometheus

- name: reload_systemd
  command: systemctl daemon-reload
  listen: reload_systemd